version: "3.7"

services:
  todoapi-db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - 5432:5432
  todoapi-node:
    container_name: app
    build: .
    depends_on:
      - todoapi-db
    ports:
      - 3030:3030
    volumes:
      - .:/home/app/
      - /home/app/node_modules
